---
- name: init microservice image file folder
  file:
    path: "{{microservice_gate_image_path}}"
    state: directory

- name: copy the image file from local
  template:
    src: "Dockerfile.template"
    dest: "{{microservice_gate_image_path}}/Dockerfile"

- name: copy the nginx conf file from local
  copy:
    src: "nginx.conf"
    dest: "{{microservice_gate_image_path}}"

- name: copy the lua-resty-mongo module to the image path
  synchronize:
    src: "./lua-resty-mongol"
    dest: "{{microservice_gate_image_path}}"

- name: copy the validation code to the image path
  synchronize:
    src: "./src/"
    dest: "{{microservice_gate_image_path}}/src"
    
- name: build the microservice_gate image
  docker_image:
    name: "{{microservice_gate_image_name}}"
    path: "{{microservice_gate_image_path}}"

...